### ISSUE TITLE
MongoDB secure?!

### ISSUE THREAD

**Issue by Dexus** [warpspeed/warpspeed#5]
Please have a look to your unsecure mongodb installer! THANK YOU!

**Comment by christurnertv** [comment]
Warpspeed is meant provide a reasonable starting point for application development. The OS firewall is configured by default to deny all incoming connections except HTTP, HTTPS, and SSH.

Mongo is configured to allow remote connections by default, but the firewall configuration would also need to be modified to actually allow this. Additionally, no role based access is provided by default and that is instead left up to the developer.

If you think default configuration should be changed then please feel free to provide constructive feedback without the use of profanity. Thanks.
